---
version: 1
disable_existing_loggers: False
formatters:
  simple:
      format: "%(asctime)s - %(name)-26s - [%(levelname)-7s] %(message)s"
  
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: out.log
    encoding: utf8

root:
  level: DEBUG
  handlers: [console, file_handler]